import http from 'node:http';
import crypto from 'node:crypto';

const PORT=Number(process.env.PORT||3000);
const EVO=String(process.env.EVOLUTION_API_URL||'').replace(/\/+$/,'');
const KEY=String(process.env.EVOLUTION_API_KEY||'');
const SECRET=String(process.env.MOTAJA_AGENT_GATEWAY_SECRET||'');
const SB=String(process.env.SUPABASE_URL||'https://qfdjiqacjeafquoscbnj.supabase.co').replace(/\/+$/,'');
const TOKEN=String(process.env.WEBHOOK_PATH_TOKEN||'');
const INSTANCE=String(process.env.EVOLUTION_INSTANCE||'motaja');
const MAX_BODY=4*1024*1024;
const clean=(v,m=1800)=>String(v??'').trim().replace(/\s+/g,' ').slice(0,m);

function equal(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function unwrap(m={}){for(let i=0;i<4;i++){if(m.ephemeralMessage?.message)m=m.ephemeralMessage.message;else if(m.viewOnceMessage?.message)m=m.viewOnceMessage.message;else if(m.viewOnceMessageV2?.message)m=m.viewOnceMessageV2.message;else break}return m}
function identity(d){const k=d?.key||{},remote=String(k.remoteJid||''),alt=String(k.remoteJidAlt||''),jid=alt.includes('@s.whatsapp.net')?alt:remote,digits=jid.split('@')[0].replace(/\D/g,'');if(!/^258\d{9}$/.test(digits))return null;return{phone:`+${digits}`,conversationKey:remote.includes('@lid')?remote:`+${digits}`}}
function textOf(msg){const m=unwrap(msg);return clean(m.conversation||m.extendedTextMessage?.text||m.imageMessage?.caption||m.videoMessage?.caption||m.documentMessage?.caption||m.buttonsResponseMessage?.selectedDisplayText||m.listResponseMessage?.title||m.templateButtonReplyMessage?.selectedDisplayText||'')}
function locationOf(msg){const m=unwrap(msg),l=m.locationMessage||m.liveLocationMessage;if(!l)return null;const lat=Number(l.degreesLatitude??l.latitude),lng=Number(l.degreesLongitude??l.longitude);return Number.isFinite(lat)&&Number.isFinite(lng)&&lat>=-90&&lat<=90&&lng>=-180&&lng<=180?{lat,lng,address:clean(l.address||l.name||'',250)||null}:null}
function sendJson(res,status,obj){const data=Buffer.from(JSON.stringify(obj));res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':String(data.length),'cache-control':'no-store','x-content-type-options':'nosniff'});res.end(data)}
async function readJson(req){let total=0;const chunks=[];for await(const chunk of req){total+=chunk.length;if(total>MAX_BODY)throw new Error('body_too_large');chunks.push(chunk)}if(!chunks.length)return{};return JSON.parse(Buffer.concat(chunks).toString('utf8'))}
async function media(data){const r=await fetch(`${EVO}/chat/getBase64FromMediaMessage/${encodeURIComponent(INSTANCE)}`,{method:'POST',headers:{'content-type':'application/json',apikey:KEY},body:JSON.stringify({message:data}),signal:AbortSignal.timeout(20000)});const raw=await r.text();if(!r.ok)throw new Error(`media_${r.status}`);const p=JSON.parse(raw),base64=String(p?.base64||'');if(!base64)throw new Error('media_empty');return{base64,mimetype:clean(p?.mimetype||'audio/ogg',100)}}
async function transcribe(x){const r=await fetch(`${SB}/functions/v1/motaja-transcribe-audio`,{method:'POST',headers:{'content-type':'application/json','x-motaja-agent-secret':SECRET},body:JSON.stringify(x),signal:AbortSignal.timeout(35000)});const p=await r.json().catch(()=>null);if(!r.ok||!p?.text)throw new Error(p?.error||`stt_${r.status}`);return clean(p.text)}
async function callAgentSlug(slug,input,timeout=35000){const r=await fetch(`${SB}/functions/v1/${slug}`,{method:'POST',headers:{'content-type':'application/json','x-motaja-agent-secret':SECRET},body:JSON.stringify(input),signal:AbortSignal.timeout(timeout)});const p=await r.json().catch(()=>null);if(!r.ok||!p)throw new Error(`${slug}_${r.status}`);return p}
async function agent(input){return callAgentSlug('motaja-whatsapp-dispatch',input,55000)}
async function send(phone,text){if(!text)return;const r=await fetch(`${EVO}/message/sendText/${encodeURIComponent(INSTANCE)}`,{method:'POST',headers:{'content-type':'application/json',apikey:KEY},body:JSON.stringify({number:phone.replace(/^\+/,''),text:String(text).slice(0,3800)}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`send_${r.status}`)}

async function webhook(body){if(body.event&&!['messages.upsert','MESSAGES_UPSERT'].includes(body.event))return{ok:true,ignored:'event'};const d=body.data||{};if(d?.key?.fromMe===true)return{ok:true,ignored:'from_me'};const remote=String(d?.key?.remoteJid||'');if(remote.endsWith('@g.us')||remote.includes('broadcast'))return{ok:true,ignored:'group'};const id=identity(d);if(!id)return{ok:true,ignored:'identity'};let message=textOf(d.message);const location=locationOf(d.message),m=unwrap(d.message);if(!message&&m.audioMessage){try{message=await transcribe(await media(d));console.log(JSON.stringify({event:'audio_transcribed',chars:message.length}))}catch(e){console.warn(JSON.stringify({event:'audio_failed',reason:clean(e?.message,120)}));await send(id.phone,'Recebi o teu áudio, mas não consegui transcrevê-lo agora. Podes repetir em texto ou enviar outro áudio?');return{ok:true,audio_failed:true}}}if(!message&&!location)return{ok:true,ignored:'empty'};const out=await agent({channel:'whatsapp',conversation_key:id.conversationKey,phone:id.phone,message,location,metadata:{source:'evolution',message_id:clean(d?.key?.id,120)||null,message_type:m.audioMessage?'audio':location?'location':'text'}});if(out?.reply&&!out?.suppress_reply)await send(id.phone,out.reply);return{ok:true,action:out?.action||null,duplicate:out?.duplicate===true}}

const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/','http://localhost');if(req.method==='GET'&&u.pathname==='/health')return sendJson(res,200,{ok:true,service:'motaja-whatsapp-gateway',version:2,idempotent:true});if(req.method!=='POST'||!u.pathname.startsWith('/webhook/'))return sendJson(res,404,{error:'not_found'});const pathToken=decodeURIComponent(u.pathname.slice('/webhook/'.length));if(!TOKEN||!equal(pathToken,TOKEN))return sendJson(res,404,{error:'not_found'});const body=await readJson(req);const out=await webhook(body);return sendJson(res,200,out)}catch(e){console.error(JSON.stringify({event:'webhook_error',reason:clean(e?.message,160)}));return sendJson(res,200,{ok:false})}});

server.listen(PORT,'0.0.0.0',async()=>{console.log(JSON.stringify({event:'gateway_started',port:PORT,version:2,idempotent:true}));if(String(process.env.AUTO_CONFIGURE_WEBHOOK||'true')!=='true'||!EVO||!KEY||!TOKEN)return;const explicit=clean(process.env.MOTAJA_GATEWAY_WEBHOOK_BASE,400),privateHost=clean(process.env.RAILWAY_PRIVATE_DOMAIN,200),base=explicit||(privateHost?`http://${privateHost}:${PORT}`:'');if(!base){console.warn(JSON.stringify({event:'webhook_not_configured',reason:'no_reachable_base'}));return}try{const url=`${base.replace(/\/+$/,'')}/webhook/${TOKEN}`;const r=await fetch(`${EVO}/webhook/set/${encodeURIComponent(INSTANCE)}`,{method:'POST',headers:{'content-type':'application/json',apikey:KEY},body:JSON.stringify({webhook:{enabled:true,url,byEvents:false,base64:false,events:['MESSAGES_UPSERT']}}),signal:AbortSignal.timeout(15000)});console.log(JSON.stringify({event:'webhook_configured',status:r.status,transport:explicit?'public':'private'}))}catch(e){console.error(JSON.stringify({event:'webhook_config_failed',reason:clean(e?.message,120)}))}});
