import express from 'express';
import crypto from 'node:crypto';
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'4mb'}));
const PORT=Number(process.env.PORT||3000),EVO=String(process.env.EVOLUTION_API_URL||'').replace(/\/+$/,''),KEY=String(process.env.EVOLUTION_API_KEY||''),SECRET=String(process.env.MOTAJA_AGENT_GATEWAY_SECRET||''),SB=String(process.env.SUPABASE_URL||'https://qfdjiqacjeafquoscbnj.supabase.co').replace(/\/+$/,''),TOKEN=String(process.env.WEBHOOK_PATH_TOKEN||''),INSTANCE=String(process.env.EVOLUTION_INSTANCE||'motaja');
const clean=(v,m=1800)=>String(v??'').trim().replace(/\s+/g,' ').slice(0,m);
function equal(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function unwrap(m={}){for(let i=0;i<4;i++){if(m.ephemeralMessage?.message)m=m.ephemeralMessage.message;else if(m.viewOnceMessage?.message)m=m.viewOnceMessage.message;else if(m.viewOnceMessageV2?.message)m=m.viewOnceMessageV2.message;else break}return m}
function identity(d){const k=d?.key||{},remote=String(k.remoteJid||''),alt=String(k.remoteJidAlt||''),jid=alt.includes('@s.whatsapp.net')?alt:remote,digits=jid.split('@')[0].replace(/\D/g,'');if(!/^258\d{9}$/.test(digits))return null;return{phone:`+${digits}`,conversationKey:remote.includes('@lid')?remote:`+${digits}`}}
function textOf(msg){const m=unwrap(msg);return clean(m.conversation||m.extendedTextMessage?.text||m.imageMessage?.caption||m.videoMessage?.caption||m.documentMessage?.caption||m.buttonsResponseMessage?.selectedDisplayText||m.listResponseMessage?.title||m.templateButtonReplyMessage?.selectedDisplayText||'')}
function locationOf(msg){const m=unwrap(msg),l=m.locationMessage||m.liveLocationMessage;if(!l)return null;const lat=Number(l.degreesLatitude??l.latitude),lng=Number(l.degreesLongitude??l.longitude);return Number.isFinite(lat)&&Number.isFinite(lng)&&lat>=-90&&lat<=90&&lng>=-180&&lng<=180?{lat,lng,address:clean(l.address||l.name||'',250)||null}:null}
async function media(data){const r=await fetch(`${EVO}/chat/getBase64FromMediaMessage/${encodeURIComponent(INSTANCE)}`,{method:'POST',headers:{'content-type':'application/json',apikey:KEY},body:JSON.stringify({message:data}),signal:AbortSignal.timeout(20000)});const raw=await r.text();if(!r.ok)throw new Error(`media_${r.status}`);const p=JSON.parse(raw),base64=String(p?.base64||'');if(!base64)throw new Error('media_empty');return{base64,mimetype:clean(p?.mimetype||'audio/ogg',100)}}
async function transcribe(x){const r=await fetch(`${SB}/functions/v1/motaja-transcribe-audio`,{method:'POST',headers:{'content-type':'application/json','x-motaja-agent-secret':SECRET},body:JSON.stringify(x),signal:AbortSignal.timeout(30000)});const p=await r.json().catch(()=>null);if(!r.ok||!p?.text)throw new Error(p?.error||`stt_${r.status}`);return clean(p.text)}
async function agent(input){const r=await fetch(`${SB}/functions/v1/motaja-agent-super-entry`,{method:'POST',headers:{'content-type':'application/json','x-motaja-agent-secret':SECRET},body:JSON.stringify(input),signal:AbortSignal.timeout(35000)});const p=await r.json().catch(()=>null);if(!r.ok||!p)throw new Error(`agent_${r.status}`);return p}
async function send(phone,text){if(!text)return;const r=await fetch(`${EVO}/message/sendText/${encodeURIComponent(INSTANCE)}`,{method:'POST',headers:{'content-type':'application/json',apikey:KEY},body:JSON.stringify({number:phone.replace(/^\+/,''),text:String(text).slice(0,3800)}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`send_${r.status}`)}
app.get('/health',(_q,res)=>res.json({ok:true,service:'motaja-whatsapp-gateway'}));
app.post('/webhook/:token',async(req,res)=>{try{if(!TOKEN||!equal(req.params.token,TOKEN))return res.status(404).end();const b=req.body||{};if(b.event&&!['messages.upsert','MESSAGES_UPSERT'].includes(b.event))return res.json({ok:true,ignored:'event'});const d=b.data||{};if(d?.key?.fromMe===true)return res.json({ok:true,ignored:'from_me'});const remote=String(d?.key?.remoteJid||'');if(remote.endsWith('@g.us')||remote.includes('broadcast'))return res.json({ok:true,ignored:'group'});const id=identity(d);if(!id)return res.json({ok:true,ignored:'identity'});let message=textOf(d.message);const location=locationOf(d.message),m=unwrap(d.message);if(!message&&m.audioMessage){try{message=await transcribe(await media(d))}catch(e){console.warn(JSON.stringify({event:'audio_failed',reason:clean(e?.message,120)}));await send(id.phone,'Recebi o teu áudio, mas não consegui transcrevê-lo agora. Podes repetir em texto ou enviar outro áudio?');return res.json({ok:true,audio_failed:true})}}if(!message&&!location)return res.json({ok:true,ignored:'empty'});const out=await agent({channel:'whatsapp',conversation_key:id.conversationKey,phone:id.phone,message,location,metadata:{source:'evolution',message_id:clean(d?.key?.id,120)||null}});if(out?.reply)await send(id.phone,out.reply);return res.json({ok:true,action:out?.action||null})}catch(e){console.error(JSON.stringify({event:'webhook_error',reason:clean(e?.message,160)}));return res.status(200).json({ok:false})}});
app.listen(PORT,'0.0.0.0',async()=>{console.log(JSON.stringify({event:'gateway_started',port:PORT}));if(String(process.env.AUTO_CONFIGURE_WEBHOOK||'true')!=='true'||!EVO||!KEY||!TOKEN)return;const explicit=clean(process.env.MOTAJA_GATEWAY_WEBHOOK_BASE,400);const privateHost=clean(process.env.RAILWAY_PRIVATE_DOMAIN,200);const base=explicit||(privateHost?`http://${privateHost}:${PORT}`:'');if(!base){console.warn(JSON.stringify({event:'webhook_not_configured',reason:'no_reachable_base'}));return}try{const url=`${base.replace(/\/+$/,'')}/webhook/${TOKEN}`;const r=await fetch(`${EVO}/webhook/set/${encodeURIComponent(INSTANCE)}`,{method:'POST',headers:{'content-type':'application/json',apikey:KEY},body:JSON.stringify({webhook:{enabled:true,url,byEvents:false,base64:false,events:['MESSAGES_UPSERT']}}),signal:AbortSignal.timeout(15000)});console.log(JSON.stringify({event:'webhook_configured',status:r.status,transport:explicit?'public':'private'}))}catch(e){console.error(JSON.stringify({event:'webhook_config_failed',reason:clean(e?.message,120)}))}});
